in_channels: 3
num_classes: 1
epochs: 100
early_stop: 25
batch_size: 8
device_ids: [0]

optimizer: AdamW
lr: 0.0001
momentum: 0.9
weight_decay: 0.0001

scheduler:
  type: CosineAnnealingLR
  T_max: 100
  eta_min: 0.000001

loss_function:
  name: DiceBCELoss
  gamma: 2.0
  reduction: mean

iterations: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
model_name: DeepLab_V3_Plus_Effi_USE_Trans2